In [1]:
import numpy as np

# Degrees of Freedom

If you experimented with changing $Q$ at all, you may have noticed it takes some effort to actually keep all the tank volumes balanced over time. When we defined each diagonal term to ensure that each column sums to zero, we saw that only under very particular circumstances did the rows also sum to zero. If we decide to ensure that each flow should be between exactly two tanks and all tank volumes should be constant, we have a new system of equations to solve (just linear equations, not differential equations). Specifically, there are 8 equations (one to set each row and column equal to zero) and 16 unknown variables (the entries of the matrix). Mathematically, the system is considered "underdetermined;" there are more variables to adjust than there are equations to relate them. And this is clearly the case, since to construct our matrix $Q$ used the 12 variables provided in the model diagram. See if you can find all 12, remembering that those with a value of 0 are not shown explicitly. These 12 variables are what we entered in $Q_h$, at which point we could calculate the remaining 4.

But did we really need all 12? It turns out that we did not. To see that this is the case, you can try "covering up" one of the flow rate labels and determine what it must be to keep all the other flows balanced. What this means is that at least one of the provided flow rates is redundant. You may wonder how many redundancies there are. I found 3. Together with the four diagonal entries we've already discussed, this means we can calculate 7 entries of $Q$ as long as we're given the other 9.

I wrote a short algorithm to do this calculation, assuming the 7 unknown entries are arranged on the diagonal and subdiagonal (sort of like an _extra_ hollow matrix).

We can check that our entire $Q$ matrix can be recovered from just 4 non-zero entries (5 zeros). Unlike the previous construction, this matrix will always have each row and each column sum to zero, just like we want. This provides a way to experiment more freely without having to balance terms manually. However, we will want to check that none of the diagonal entries are positive, and none of the subdiagonal entries are negative.

In [2]:
# number of tanks 
n = 4

# empty diagonal and subdiagonal
Xt = np.array([[0, 2, 10, 6],
               [0, 0, 4, 0],
               [0, 0, 0, 2],
               [10, 0, 0, 0]]) # L/hr

def fill_matrix(M):
    for i in range(n - 1):
        np.put(M, [i * n + i], -M.sum(axis=1)[i])
        np.put(M, [(i + 1) * n + i], -M.sum(axis=0)[i])
    np.put(M, [(n - 1) * n + (n - 1)], -M.sum(axis=1)[3])
    return M



print("- - - - - - - - - - - -")

print(fill_matrix(Xt))

print("- - - - - - - - - - - -")

print(f"Diagonal Sign Check: {np.diagonal(Xt) <= 0}")
print(f"Subiagonal Sign Check: {np.diagonal(Xt, -1) >= 0}")

- - - - - - - - - - - -
[[-18   2  10   6]
 [  8 -12   4   0]
 [  0  10 -12   2]
 [ 10   0  -2  -8]]
- - - - - - - - - - - -
Diagonal Sign Check: [ True  True  True  True]
Subiagonal Sign Check: [ True  True False]
